pipeline {

    agent any

    stages {
        stage('Build Jar') {
            agent{
                docker {
                    image 'maven:3.9.3-eclipse-temurin-17-focal'
                    args '-u root -v /tmp/m2:/root/.m2' 
                }
            }
            steps {
                echo 'Building Project Jar...'
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Create Image') {
            steps {
                echo 'Building Docker Image...'
                 script {
                    app = docker.build('jagatheshwarann/selenium')
                }
            }
        }
        stage('Deploy Image') {
           script {
                    // registry url is blank for dockerhub
                    docker.withRegistry('', 'Docker') {
                        app.push("latest")
                    }
                }
        }
    }
    post {
        always {
            bat "docker logout"
        }
    }

}